### ISSUE TITLE
Overflowing todo

### ISSUE THREAD

**Issue by CJaclyn** [Hack-Weekly/golden-dragon#4]
This can easily be fixed with one CSS property 😄

![Screenshot 2023-03-12 162446](https://user-images.githubusercontent.com/44209123/224574572-1368cd87-e6a8-4fc7-9975-5f57f3dd5860.jpg)

**Comment by diego-rapoport** [comment]
Is it about to be done or can I assume this task? The showcases are about to begin shortly.

**Comment by CJaclyn** [comment]
> Is it about to be done or can I assume this task? The showcases are about to begin shortly.

You can do it!

**Comment by diego-rapoport** [comment]
#5 fixes this
